name: Test portal-server
on: [push, pull_request]

jobs:
  test_proxy:
    defaults:
      run:
        working-directory: metrics
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
    - name: Install python dependencies
      run: pip install -r requirements.txt && pip install -r requirements-dev.txt
    - name: Lint with ruff
      run: ruff check app/
